http_server:
  host: "localhost"
  port: "9999"

mysql_master:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "123456"
  dbname: "code_comment_analyzer"

user_token_duration: 5  # min
jwt_key: secret_key_for_user