http_server:
  host: "localhost"
  port: "9999"

mysql_master:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "123456"
  dbname: "code_comment_analyzer"

redis_master:
  host: "localhost"
  port: "6379"
  password:
  db: 0
  prefix_session: "ss_"

ccanalyzer_conf:
  host: "localhost"
  port: "8888"

user_token_duration: 5  # min
jwt_key: secret_key_for_user

default_nickname: "Anonymous"
default_avatar: "default_avatar.jpg"

max_file_size: 10  # MB
max_project_size: 100  # MB

file_storage_path:
  avatar: "file_storage/avatars"
  projects: "file_storage/projects"