// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: ccanalyzer.proto

package ccanalyzer_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CcAnalyzer_AnalyzeFileContent_FullMethodName = "/CcAnalyzer/AnalyzeFileContent"
)

// CcAnalyzerClient is the client API for CcAnalyzer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CcAnalyzerClient interface {
	AnalyzeFileContent(ctx context.Context, in *AnalyzeFileContentReq, opts ...grpc.CallOption) (*AnalyzeFileContentRes, error)
}

type ccAnalyzerClient struct {
	cc grpc.ClientConnInterface
}

func NewCcAnalyzerClient(cc grpc.ClientConnInterface) CcAnalyzerClient {
	return &ccAnalyzerClient{cc}
}

func (c *ccAnalyzerClient) AnalyzeFileContent(ctx context.Context, in *AnalyzeFileContentReq, opts ...grpc.CallOption) (*AnalyzeFileContentRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeFileContentRes)
	err := c.cc.Invoke(ctx, CcAnalyzer_AnalyzeFileContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CcAnalyzerServer is the server API for CcAnalyzer service.
// All implementations must embed UnimplementedCcAnalyzerServer
// for forward compatibility.
type CcAnalyzerServer interface {
	AnalyzeFileContent(context.Context, *AnalyzeFileContentReq) (*AnalyzeFileContentRes, error)
	mustEmbedUnimplementedCcAnalyzerServer()
}

// UnimplementedCcAnalyzerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCcAnalyzerServer struct{}

func (UnimplementedCcAnalyzerServer) AnalyzeFileContent(context.Context, *AnalyzeFileContentReq) (*AnalyzeFileContentRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeFileContent not implemented")
}
func (UnimplementedCcAnalyzerServer) mustEmbedUnimplementedCcAnalyzerServer() {}
func (UnimplementedCcAnalyzerServer) testEmbeddedByValue()                    {}

// UnsafeCcAnalyzerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CcAnalyzerServer will
// result in compilation errors.
type UnsafeCcAnalyzerServer interface {
	mustEmbedUnimplementedCcAnalyzerServer()
}

func RegisterCcAnalyzerServer(s grpc.ServiceRegistrar, srv CcAnalyzerServer) {
	// If the following call pancis, it indicates UnimplementedCcAnalyzerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CcAnalyzer_ServiceDesc, srv)
}

func _CcAnalyzer_AnalyzeFileContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeFileContentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CcAnalyzerServer).AnalyzeFileContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CcAnalyzer_AnalyzeFileContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CcAnalyzerServer).AnalyzeFileContent(ctx, req.(*AnalyzeFileContentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CcAnalyzer_ServiceDesc is the grpc.ServiceDesc for CcAnalyzer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CcAnalyzer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CcAnalyzer",
	HandlerType: (*CcAnalyzerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeFileContent",
			Handler:    _CcAnalyzer_AnalyzeFileContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ccanalyzer.proto",
}
