// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.2
// source: ccanalyzer.proto

package ccanalyzer_client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeFileContentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language    string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	FileContent string `protobuf:"bytes,2,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
}

func (x *AnalyzeFileContentReq) Reset() {
	*x = AnalyzeFileContentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ccanalyzer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyzeFileContentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFileContentReq) ProtoMessage() {}

func (x *AnalyzeFileContentReq) ProtoReflect() protoreflect.Message {
	mi := &file_ccanalyzer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFileContentReq.ProtoReflect.Descriptor instead.
func (*AnalyzeFileContentReq) Descriptor() ([]byte, []int) {
	return file_ccanalyzer_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeFileContentReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AnalyzeFileContentReq) GetFileContent() string {
	if x != nil {
		return x.FileContent
	}
	return ""
}

type AnalyzeFileContentRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 使用 google.protobuf.Struct 表示动态键值对
	AnalyzedData *structpb.Struct `protobuf:"bytes,1,opt,name=analyzed_data,json=analyzedData,proto3" json:"analyzed_data,omitempty"`
}

func (x *AnalyzeFileContentRes) Reset() {
	*x = AnalyzeFileContentRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ccanalyzer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalyzeFileContentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFileContentRes) ProtoMessage() {}

func (x *AnalyzeFileContentRes) ProtoReflect() protoreflect.Message {
	mi := &file_ccanalyzer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFileContentRes.ProtoReflect.Descriptor instead.
func (*AnalyzeFileContentRes) Descriptor() ([]byte, []int) {
	return file_ccanalyzer_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeFileContentRes) GetAnalyzedData() *structpb.Struct {
	if x != nil {
		return x.AnalyzedData
	}
	return nil
}

var File_ccanalyzer_proto protoreflect.FileDescriptor

var file_ccanalyzer_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x63, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x56, 0x0a, 0x15, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x6c,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x55, 0x0a, 0x15, 0x41, 0x6e, 0x61, 0x6c,
	0x79, 0x7a, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x12, 0x3c, 0x0a, 0x0d, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x64, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x52, 0x0c, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x32,
	0x52, 0x0a, 0x0a, 0x43, 0x63, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x12, 0x44, 0x0a,
	0x12, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x7a, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x3b, 0x63, 0x63, 0x61, 0x6e, 0x61, 0x6c, 0x79,
	0x7a, 0x65, 0x72, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ccanalyzer_proto_rawDescOnce sync.Once
	file_ccanalyzer_proto_rawDescData = file_ccanalyzer_proto_rawDesc
)

func file_ccanalyzer_proto_rawDescGZIP() []byte {
	file_ccanalyzer_proto_rawDescOnce.Do(func() {
		file_ccanalyzer_proto_rawDescData = protoimpl.X.CompressGZIP(file_ccanalyzer_proto_rawDescData)
	})
	return file_ccanalyzer_proto_rawDescData
}

var file_ccanalyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ccanalyzer_proto_goTypes = []interface{}{
	(*AnalyzeFileContentReq)(nil), // 0: AnalyzeFileContentReq
	(*AnalyzeFileContentRes)(nil), // 1: AnalyzeFileContentRes
	(*structpb.Struct)(nil),       // 2: google.protobuf.Struct
}
var file_ccanalyzer_proto_depIdxs = []int32{
	2, // 0: AnalyzeFileContentRes.analyzed_data:type_name -> google.protobuf.Struct
	0, // 1: CcAnalyzer.AnalyzeFileContent:input_type -> AnalyzeFileContentReq
	1, // 2: CcAnalyzer.AnalyzeFileContent:output_type -> AnalyzeFileContentRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ccanalyzer_proto_init() }
func file_ccanalyzer_proto_init() {
	if File_ccanalyzer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ccanalyzer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyzeFileContentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ccanalyzer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalyzeFileContentRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ccanalyzer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ccanalyzer_proto_goTypes,
		DependencyIndexes: file_ccanalyzer_proto_depIdxs,
		MessageInfos:      file_ccanalyzer_proto_msgTypes,
	}.Build()
	File_ccanalyzer_proto = out.File
	file_ccanalyzer_proto_rawDesc = nil
	file_ccanalyzer_proto_goTypes = nil
	file_ccanalyzer_proto_depIdxs = nil
}
