// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: ccanalyzer.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CCAnalyzer_SayHello_FullMethodName = "/CCAnalyzer/SayHello"
)

// CCAnalyzerClient is the client API for CCAnalyzer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CCAnalyzerClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type cCAnalyzerClient struct {
	cc grpc.ClientConnInterface
}

func NewCCAnalyzerClient(cc grpc.ClientConnInterface) CCAnalyzerClient {
	return &cCAnalyzerClient{cc}
}

func (c *cCAnalyzerClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, CCAnalyzer_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CCAnalyzerServer is the server API for CCAnalyzer service.
// All implementations must embed UnimplementedCCAnalyzerServer
// for forward compatibility.
type CCAnalyzerServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedCCAnalyzerServer()
}

// UnimplementedCCAnalyzerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCCAnalyzerServer struct{}

func (UnimplementedCCAnalyzerServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedCCAnalyzerServer) mustEmbedUnimplementedCCAnalyzerServer() {}
func (UnimplementedCCAnalyzerServer) testEmbeddedByValue()                    {}

// UnsafeCCAnalyzerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CCAnalyzerServer will
// result in compilation errors.
type UnsafeCCAnalyzerServer interface {
	mustEmbedUnimplementedCCAnalyzerServer()
}

func RegisterCCAnalyzerServer(s grpc.ServiceRegistrar, srv CCAnalyzerServer) {
	// If the following call pancis, it indicates UnimplementedCCAnalyzerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CCAnalyzer_ServiceDesc, srv)
}

func _CCAnalyzer_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CCAnalyzerServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CCAnalyzer_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CCAnalyzerServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CCAnalyzer_ServiceDesc is the grpc.ServiceDesc for CCAnalyzer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CCAnalyzer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CCAnalyzer",
	HandlerType: (*CCAnalyzerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _CCAnalyzer_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ccanalyzer.proto",
}
