// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	UserFilerecord      string
	UserOperatingrecord string
	UserProjectrecord   string
	UserUser            string
}{
	UserFilerecord:      "user_filerecord",
	UserOperatingrecord: "user_operatingrecord",
	UserProjectrecord:   "user_projectrecord",
	UserUser:            "user_user",
}
